### Healthcheck
GET http://localhost:4000/v1/healthcheck

### Get all movies
GET http://localhost:4000/v1/movies

#### Create a movies
POST http://localhost:4000/v1/movies
Content-Type: application/json

{
   "title":"The Breakfast Club",
   "year":1986,
   "runtime":"96 mins",
   "genres":[
      "drama"
   ]
}

### Get movies by ID
GET http://localhost:4000/v1/movies/8

### Udpate an user
PATCH  http://localhost:4000/v1/movies/6
Content-Type: application/json

{
   "year": 2015
}

### Delete movies by ID
DELETE http://localhost:4000/v1/movies/7